/**
 * Deep-Link Rendering Tests (Phase 4: Visual Integration)
 * 
 * These tests verify that the deep-link URLs generated by the MCP
 * calculate_zakat tool correctly render results in the web app.
 * 
 * NOTE: This tests the DEEP-LINK flow (user clicks through from ChatGPT
 * to zakatflow.org). For testing the actual MCP widget rendering inside
 * ChatGPT, see run-agentic-evals.ts which tests against real LLM APIs.
 * 
 * Deep-link flow:
 *   1. URL with `?data=<base64-encoded-formData>` is loaded
 *   2. useCalculatorDeepLink hook hydrates formData and jumps to results step
 *   3. Results page renders with zakat-due-amount data-testid
 * 
 * See: docs/PRDs/eval-infrastructure.md
 * See: apps/web/src/hooks/useCalculatorDeepLink.ts
 */

import { test, expect } from '@playwright/test';
import { clearAppState } from './helpers/wizard-helpers';

// =============================================================================
// Helper: Generate a deep-link URL from a ZakatFormData payload
// =============================================================================

function buildDeepLink(formDataOverrides: Record<string, unknown>): string {
    const compact: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(formDataOverrides)) {
        // Strip defaults and zero values to match MCP tool's compact encoding
        if (value === 0 || value === '' || value === false) continue;
        if (key === 'age' && value === 30) continue;
        if (key === 'nisabStandard' && value === 'silver') continue;
        if (key === 'householdMembers') continue;
        compact[key] = value;
    }

    const encoded = Buffer.from(JSON.stringify(compact)).toString('base64');
    return `/?data=${encoded}&utm_source=chatgpt&utm_medium=widget`;
}

// =============================================================================
// Deep-Link → Web App Rendering Tests
// =============================================================================

test.describe('Deep-Link Rendering (Phase 4)', () => {

    test.beforeEach(async ({ page, context }) => {
        await clearAppState(page, context);
    });

    test('Payload: $50k cash renders results page with Zakat amount', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 50000,
            madhab: 'bradford',
        });
        await page.goto(deepLink);

        // The deep-link hydrates data and jumps to results step (index 17)
        // Wait for the ReportHero zakat-due-amount element
        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        const zakatText = await page.textContent('[data-testid="zakat-due-amount"]');
        expect(zakatText).toBeTruthy();
        // $50,000 * 2.5% = $1,250
        expect(zakatText).toContain('$');
    });

    test('Payload: Multi-asset portfolio renders without crash', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 25000,
            passiveInvestmentsValue: 100000,
            goldJewelryValue: 10000,
            hasPreciousMetals: true,
            fourOhOneKVestedBalance: 200000,
            creditCardBalance: 5000,
            monthlyMortgage: 2000,
            madhab: 'hanafi',
            age: 35,
        });
        await page.goto(deepLink);

        // Should render the results page with zakat amount
        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        const zakatText = await page.textContent('[data-testid="zakat-due-amount"]');
        expect(zakatText).toBeTruthy();
    });

    test('Payload: Below-nisab amount renders $0 or below-nisab message', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 100,
            madhab: 'bradford',
        });
        await page.goto(deepLink);

        // Even below nisab, the results page should still render
        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        const zakatText = await page.textContent('[data-testid="zakat-due-amount"]');
        expect(zakatText).toBeTruthy();
        // Should show $0
        expect(zakatText).toContain('$0');
    });

    test('Deep-link includes utm_source=chatgpt in the initial URL', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 10000,
            madhab: 'bradford',
        });

        // Verify the generated link format before navigating
        expect(deepLink).toContain('utm_source=chatgpt');
        expect(deepLink).toContain('utm_medium=widget');
        expect(deepLink).toContain('data=');

        // Navigate — the hook strips the data param after processing
        await page.goto(deepLink);

        // Results should render (confirming the deep-link was consumed)
        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });
    });

    test('Multiple madhab payloads render without errors', async ({ page }) => {
        test.setTimeout(120000);

        const madhabs = ['bradford', 'hanafi', 'shafii'];

        for (const madhab of madhabs) {
            const deepLink = buildDeepLink({
                checkingAccounts: 10000,
                madhab,
            });
            await page.goto(deepLink);

            // Wait for results to render
            const zakatEl = await page.waitForSelector('[data-testid="zakat-due-amount"]', {
                timeout: 20000,
            }).catch(() => null);

            // Should render without crash
            expect(zakatEl, `Madhab ${madhab} failed to render results`).toBeTruthy();
        }
    });
});

// =============================================================================
// Ahmed Matrix Deep-Link Rendering
// =============================================================================

test.describe('Deep-Link: Ahmed Matrix Payloads (Phase 4)', () => {

    test.beforeEach(async ({ page, context }) => {
        await clearAppState(page, context);
    });

    test('Ahmed Hanafi deep-link renders results', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 100000,
            fourOhOneKVestedBalance: 200000,
            passiveInvestmentsValue: 150000,
            goldJewelryValue: 10000,
            hasPreciousMetals: true,
            creditCardBalance: 5000,
            monthlyMortgage: 2000,
            monthlyLivingExpenses: 3000,
            age: 35,
            madhab: 'hanafi',
        });
        await page.goto(deepLink);

        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        const zakatText = await page.textContent('[data-testid="zakat-due-amount"]');
        expect(zakatText).toBeTruthy();
        expect(zakatText).toContain('$');
    });

    test('Ahmed Bradford deep-link renders results', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 100000,
            fourOhOneKVestedBalance: 200000,
            passiveInvestmentsValue: 150000,
            goldJewelryValue: 10000,
            hasPreciousMetals: true,
            creditCardBalance: 5000,
            monthlyMortgage: 2000,
            monthlyLivingExpenses: 3000,
            age: 35,
            madhab: 'bradford',
        });
        await page.goto(deepLink);

        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        const zakatText = await page.textContent('[data-testid="zakat-due-amount"]');
        expect(zakatText).toBeTruthy();
    });
});

// =============================================================================
// Accessibility Verification (WCAG 2.1 AA)
// =============================================================================

test.describe('Deep-Link Accessibility (Phase 4)', () => {

    test.beforeEach(async ({ page, context }) => {
        await clearAppState(page, context);
    });

    test('Results page has proper heading hierarchy', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 50000,
            madhab: 'bradford',
        });
        await page.goto(deepLink);

        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        // Check heading hierarchy — should have at least one h1 or h2
        const headings = await page.$$eval('h1, h2, h3', els => els.map(e => ({
            tag: e.tagName.toLowerCase(),
            text: e.textContent?.trim(),
        })));

        expect(headings.length).toBeGreaterThan(0);
    });

    test('Interactive elements have accessible labels', async ({ page }) => {
        test.setTimeout(60000);

        const deepLink = buildDeepLink({
            checkingAccounts: 50000,
            madhab: 'bradford',
        });
        await page.goto(deepLink);

        await page.waitForSelector('[data-testid="zakat-due-amount"]', {
            timeout: 20000,
        });

        // Check that buttons have accessible text
        const buttons = await page.$$eval('button', els =>
            els.map(e => ({
                text: e.textContent?.trim(),
                ariaLabel: e.getAttribute('aria-label'),
            }))
        );

        for (const btn of buttons) {
            const hasLabel = (btn.text && btn.text.length > 0) || (btn.ariaLabel && btn.ariaLabel.length > 0);
            expect(hasLabel, `Button without accessible label: ${JSON.stringify(btn)}`).toBe(true);
        }
    });
});
