-- Function to calculate recursive referral stats (multi-level)
-- This traverses the referral tree:
-- 1. Starts with the given referral code (User A)
-- 2. Finds all sessions (User B) that were referred by User A's code
-- 3. Finds the referral codes generated by User B (Code B)
-- 4. Repeats for anyone referred by Code B, etc.

CREATE OR REPLACE FUNCTION public.get_recursive_referral_stats(
  p_referral_code TEXT,
  p_session_hash TEXT DEFAULT NULL
)
RETURNS TABLE (
  total_referrals BIGINT,
  total_zakat_calculated NUMERIC,
  total_assets_calculated NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_start_code TEXT;
BEGIN
  -- If session hash is provided but no code, try to find the code for that session
  -- This handles the case where we look up by session
  IF p_referral_code IS NULL AND p_session_hash IS NOT NULL THEN
    SELECT referral_code INTO v_start_code 
    FROM referral_aggregates 
    WHERE referrer_session_hash = p_session_hash;
  ELSE
    v_start_code := p_referral_code;
  END IF;

  -- If still no code found (e.g. user hasn't generated one yet), return 0s
  IF v_start_code IS NULL THEN
    RETURN QUERY SELECT 0::BIGINT, 0::NUMERIC, 0::NUMERIC;
    RETURN;
  END IF;

  RETURN QUERY
  WITH RECURSIVE referral_tree AS (
    -- Base case: Direct referrals
    -- Find people referred by the starting code
    SELECT 
      r.referred_session_hash,
      r.zakat_due,
      r.total_assets,
      1 as depth
    FROM referrals r
    WHERE r.referral_code = v_start_code

    UNION ALL

    -- Recursive case: Find people referred by the people we found
    SELECT 
      child.referred_session_hash,
      child.zakat_due,
      child.total_assets,
      rt.depth + 1
    FROM referrals child
    -- Join: We need to find the referral code that the *referred person* (rt.referred_session_hash) generated
    JOIN referral_aggregates ra ON ra.referrer_session_hash = rt.referred_session_hash
    JOIN referral_tree rt ON child.referral_code = ra.referral_code
    -- Prevent infinite loops just in case
    WHERE rt.depth < 20
  )
  SELECT 
    COUNT(*)::BIGINT as total_referrals,
    COALESCE(SUM(zakat_due), 0) as total_zakat_calculated,
    COALESCE(SUM(total_assets), 0) as total_assets_calculated
  FROM referral_tree;
END;
$$;
